# ====================================
# StorageSlots Configuration
# ====================================
# This file contains ONLY configuration options. All messages are in messages.yml.

# ------------------------------
# Storage Settings
# ------------------------------
storage:
  slots: 9  # Number of regular storage slots (1-54)
  default-cost: 1000.0  # Default cost for slots without specific pricing
  require-progression: true  # Whether players must unlock slots in order
  max-items-per-slot: 64  # Maximum items per slot
  costs:
    slot-1: 1000
    slot-2: 2500
    slot-3: 5000
    slot-4: 10000
    slot-5: 25000
    slot-6: 50000
    slot-7: 100000
    slot-8: 250000
    slot-9: 500000
  prohibited-items:
    - BEDROCK
    - BARRIER
    - COMMAND_BLOCK
    - STRUCTURE_BLOCK
    - STRUCTURE_VOID
    - LIGHT
    - DEBUG_STICK
    - KNOWLEDGE_BOOK

# ------------------------------
# Rank Requirements
# ------------------------------
ranks:
  slot-requirements:
    slot-1: "rank.i"
    slot-2: "rank.h"
    slot-3: "rank.g"
    slot-4: "rank.f"
    slot-5: "rank.e"
    slot-6: "rank.d"
    slot-7: "rank.c"
    slot-8: "rank.b"
    slot-9: "rank.a"
  display-names:
    "rank.i": "<yellow>I-Rank</yellow>"
    "rank.h": "<green>H-Rank</green>"
    "rank.g": "<dark_green>G-Rank</dark_green>"
    "rank.f": "<aqua>F-Rank</aqua>"
    "rank.e": "<blue>E-Rank</blue>"
    "rank.d": "<dark_purple>D-Rank</dark_purple>"
    "rank.c": "<light_purple>C-Rank</light_purple>"
    "rank.b": "<pink>B-Rank</pink>"
    "rank.a": "<red>A-Rank</red>"

# ------------------------------
# Safezone Settings
# ------------------------------
safezone:
  enabled: true
  detection-method: "pvp"  # "region", "world", or "pvp"
  region-name: "safezone"
  pvp-priority: 0
  worlds:
    - "spawn"
    - "lobby"

# ------------------------------
# Donor System
# ------------------------------
donor:
  enabled: true
  ranks:
    supporter:
      display-name: "<gray><bold>SUPPORTER</bold></gray>"
      permission: "storageslots.donor.supporter"
      slots: 1
      features:
        - "reduced_withdrawal_fees"
    vip:
      display-name: "<green><bold>VIP</bold></green>"
      permission: "storageslots.donor.vip"
      slots: 2
      features:
        - "reduced_withdrawal_fees"
        - "faster_slot_access"
    mvp:
      display-name: "<aqua><bold>MVP</bold></aqua>"
      permission: "storageslots.donor.mvp"
      slots: 4
      features:
        - "free_withdrawal"
        - "faster_slot_access"
        - "slot_discount"
    king:
      display-name: "<gold><bold>KING</bold></gold>"
      permission: "storageslots.donor.king"
      slots: 5
      features:
        - "free_withdrawal"
        - "faster_slot_access"
        - "slot_discount"
        - "priority_support"
    
  slots:
    separate: true  # Donor slots are separate from regular slots
    persist: true   # Donor slots are permanent
    purchasable: true  # Donor slots can be purchased
    cost-multiplier: 2.0  # Cost multiplier for donor slots if purchasable

# ------------------------------
# Withdrawal Fees
# ------------------------------
# Withdrawal fees are charged when players take items out of storage
# Fees are based on the player's rank, not the slot type
withdrawal-fees:
  # Enable/disable withdrawal fees entirely
  enabled: true
  
  # Default fees for players without specific rank permissions
  default:
    points: 10
    money: 100.0
  
  # Rank group fees (players with these ranks get these fees)
  # Groups are checked in order - first match wins
  rank-groups:
    # CA Ranks: Rank C, Rank B, Rank A (highest ranks)
    ca:
      ranks:
        - "rank.c"
        - "rank.b" 
        - "rank.a"
      points: 1
      money: 10.0
    
    # FD Ranks: Rank F, Rank E, Rank D (middle ranks)
    fd:
      ranks:
        - "rank.f"
        - "rank.e"
        - "rank.d"
      points: 3
      money: 30.0
    
    # JG Ranks: Rank J, Rank I, Rank H, Rank G (lower ranks)
    jg:
      ranks:
        - "rank.j"  # If you have J rank
        - "rank.i"
        - "rank.h"
        - "rank.g"
      points: 5
      money: 50.0
  
  # Individual rank overrides (these take priority over group fees)
  # Useful for fine-tuning specific ranks
  individual-ranks:
    # Example: Give A-rank players completely free withdrawals
    "rank.a":
      points: 0
      money: 0.0
    # Example: Custom fee for a specific rank
    # "rank.special":
    #   points: 2
    #   money: 20.0
  
  # Donor rank fees (donors get special treatment)
  donor:
    # Supporters get reduced fees
    supporter:
      points: 5  # 50% of default
      money: 50.0
    
    # VIP gets even more reduced fees  
    vip:
      points: 3
      money: 30.0
    
    # MVP and King get free withdrawals
    mvp:
      points: 0
      money: 0.0
    
    king:
      points: 0
      money: 0.0

# ------------------------------
# Withdrawal Cooldown
# ------------------------------
withdrawal-cooldown:
  enabled: true
  duration-ms: 1500  # 1.5 seconds in milliseconds
  apply-to-ops: true  # Whether OPs are affected by cooldown
  # Note: Players with 'storageslots.bypass.cooldown' permission can bypass cooldown

# ------------------------------
# Economy Settings
# ------------------------------
economy:
  currency-name: "points"
  use-vault: false

# ------------------------------
# Security Settings
# ------------------------------
security:
  max-slots-per-player: 9
  prevent-item-duplication: true
  log-transactions: true

# ------------------------------
# Auto-Save Settings
# ------------------------------
auto-save:
  enabled: true
  interval: 300  # In seconds (minimum 60)

# ------------------------------
# Debug Settings
# ------------------------------
debug:
  enabled: true
  log-safezone-checks: false
  log-permission-checks: false